### PR TITLE
Fix for issue #18

### PR DESCRIPTION
**Pull request by arturzx**
I've made fix for issue #18. Chunk file upload leads to file with zeroes and last chunk. Problem is 'wb' mode when opening file. This mode always truncating file and seek() to chunk offset leads to fill file with zeroes.

My patch changes file creation - open with 'wb' mode and write one \0 byte at file_size-1 offset, this operation creates sparse file with proper size, and chunk writes to file opened with 'r+b' mode - read and write, without truncating.

### CODE REVIEW

**Comment by jsproull** [comment]
👍  Thanks so much @arturzx !!

**Comment by jsproull** [comment]
@alican any chance we can get a version with this PR?

**Comment by alican** [comment]
> @alican any chance we can get a version with this PR?

Hey @jsproull , Thanky you for your pull request. I will check it tonight and merge it to the master branch.

**Comment by RubenGarcia** [comment]
Won't this overwrite the last byte of the previous chunk with a '\0' if it was already received?

**Pull request merged**
